# Importing the libraries

In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [52]:
tf.__version__

'2.13.0'

# Part 1. Data preprocessing

In [53]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


# Splitting the dataset into train and test sets

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size =0.2, random_state=0)

# Part 2. Building the ANN

In [55]:
ann = tf.keras.models.Sequential()

# Adding the input layer and first hidden layer)

In [56]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

# Adding the second hidden layer

In [57]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

# Adding the output layer

In [58]:
ann.add(tf.keras.layers.Dense(units = 1))

# Part 3. Training the ANN

# Compiling the ANN

In [59]:
ann.compile(optimizer= 'adam', loss = 'mean_squared_error')

# Training the ANN model on the Training set

In [60]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 950us/step - loss: 121025.5938
Epoch 2/100
240/240 [==============================] - 0s 988us/step - loss: 457.0096
Epoch 3/100
240/240 [==============================] - 0s 944us/step - loss: 378.8654
Epoch 4/100
240/240 [==============================] - 0s 868us/step - loss: 367.6532
Epoch 5/100
240/240 [==============================] - 0s 888us/step - loss: 355.0664
Epoch 6/100
240/240 [==============================] - 0s 899us/step - loss: 340.1019
Epoch 7/100
240/240 [==============================] - 0s 893us/step - loss: 323.5185
Epoch 8/100
240/240 [==============================] - 0s 963us/step - loss: 305.5293
Epoch 9/100
240/240 [==============================] - 0s 946us/step - loss: 286.3132
Epoch 10/100
240/240 [==============================] - 0s 946us/step - loss: 265.6662
Epoch 11/100
240/240 [==============================] - 0s 971us/step - loss: 244.5252
Epoch 12/100
240/240 [===========================

240/240 [==============================] - 0s 796us/step - loss: 26.7615
Epoch 97/100
240/240 [==============================] - 0s 720us/step - loss: 27.0053
Epoch 98/100
240/240 [==============================] - 0s 890us/step - loss: 27.0670
Epoch 99/100
240/240 [==============================] - 0s 940us/step - loss: 26.8368
Epoch 100/100
240/240 [==============================] - 0s 882us/step - loss: 26.9495


# Predict the results of the test set

In [62]:
Y_pred = ann.predict(X_test)
np.set_printoptions(precision =1)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

60/60 [==============================] - 0s 661us/step
[[430.8 431.2]
 [462.  460. ]
 [465.5 461.1]
 ...
 [472.7 473.3]
 [439.6 438. ]
 [458.8 463.3]]
